services:
  app:
    build:
      context: .
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: [ "pnpm", "run", "dev", "--host" ]

volumes:
  node_modules:
